spring:
  application:
    name: proyecto-final-backend
  flyway:
    baseline-on-migrate: true
  jwt:
    secret: ${SPRING_JWT_SECRET}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800