package org.ezequiel.proyectofinal.features.hr.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Schema(name = "RegionResponseDTO", description = "API response with complete geographic region information")
public class RegionResponseDTO {

    @Schema(
            name = "regionId",
            description = "Unique identifier for the region. Auto-generated by the system.",
            example = "1",
            accessMode = Schema.AccessMode.READ_ONLY
    )
    private Short regionId;

    @Schema(
            name = "regionDescription",
            description = "Geographic region description. Represents defined geographic areas where employees manage territories and operations.",
            example = "North"
    )
    private String regionDescription;
}
