package org.ezequiel.proyectofinal.features.hr.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Schema(name = "UsStateResponseDTO", description = "API response with complete US state reference information")
public class UsStateResponseDTO {

    @Schema(
            name = "stateId",
            description = "Unique identifier for the US state. Auto-generated by the system.",
            example = "1",
            accessMode = Schema.AccessMode.READ_ONLY
    )
    private Short stateId;

    @Schema(
            name = "stateName",
            description = "Full name of the US state used for business location reference and regional organization.",
            example = "California"
    )
    private String stateName;

    @Schema(
            name = "stateAbbr",
            description = "Standard two-letter postal abbreviation of the US state.",
            example = "CA"
    )
    private String stateAbbr;

    @Schema(
            name = "stateRegion",
            description = "Geographic or business region to which this state belongs.",
            example = "West"
    )
    private String stateRegion;
}
