### Login: Inicio de sesión para obtener tokens
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "{{userAdmin}}",
  "password": "{{pass}}"
}

> {%
    client.global.set("auth_token", response.body["token"]);
    client.global.set("refresh_token", response.body["refreshToken"]);

    client.log("Token guardado: " + client.global.get("auth_token"));
%}