@endpointLogin = {{host}}/auth/login
@endpoint = {{host}}/regions
@getOne = 1

### Login Consulta
POST {{endpointLogin}}
Content-Type: application/json

{
  "username": "{{userConsulta}}",
  "password": "{{pass}}"
}

> {%
    client.assert(response.status === 200, "El login falló");
    let jwt = response.body["token"];
    client.global.set("auth_token", jwt);
    client.log("¡Token capturado con éxito!");
%}


### GET All
GET {{endpoint}}
Authorization: Bearer {{auth_token}}


### GET by ID
GET {{endpoint}}/{{getOne}}
Authorization: Bearer {{auth_token}}


### POST Fallido (403)
POST {{endpoint}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "regionDescription": "Región Prohibida"
}

> {%
    client.assert(response.status === 403, "No se esperaba que el usuario tuviera permisos");
%}


### Login Autorizado (GESTOR)
POST {{endpointLogin}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "username": "{{userGestor}}",
  "password": "{{pass}}"
}

> {%
    client.assert(response.status === 200, "El login falló");
    let jwt = response.body["token"];
    client.global.set("auth_token", jwt);
    client.log("¡Token de Gestor capturado!");
%}


### POST Exitoso (201)
POST {{endpoint}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "regionDescription": "Nueva Región"
}

> {%
    client.assert(response.status === 201, "No se ha creado la región");
    let nuevoId = response.body["regionId"];
    client.global.set("created_region_id", nuevoId);
    client.log("Creado con el ID: " + nuevoId);
%}


### GET Verificación
GET {{endpoint}}/{{created_region_id}}
Authorization: Bearer {{auth_token}}


### PUT (Update)
PUT {{endpoint}}/{{created_region_id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "regionDescription": "Región Actualizada"
}


### DELETE
DELETE {{endpoint}}/{{created_region_id}}
Authorization: Bearer {{auth_token}}


### GET (404/Verificación)
GET {{endpoint}}/{{created_region_id}}
Authorization: Bearer {{auth_token}}

> {%
    client.assert(response.status === 404, "El recurso debería haber sido borrado");
%}
