@endpointLogin = {{host}}/auth/login
@endpoint = {{host}}/suppliers
@getOne = 1
@id = 50

### Login
POST {{endpointLogin}}
Content-Type: application/json

{
  "username": "{{userConsulta}}",
  "password": "{{pass}}"
}

> {%
    client.assert(response.status === 200, "El login falló");
    let jwt = response.body["token"];
    // Guardamos el token en una variable global de IntelliJ
    client.global.set("auth_token", jwt);

    client.log("¡Token capturado con éxito!");
%}


### Probar endpoint de traer todos
GET {{endpoint}}
# Aquí inyectamos la variable que acabamos de guardar
Authorization: Bearer {{auth_token}}


### Probar traer solo 1
GET {{endpoint}}/{{getOne}}
Authorization: Bearer {{auth_token}}


### Crear
POST {{endpoint}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "supplierId": {{id}},
  "companyName": "Nombre falso",
  "contactName": "Alguien",
  "contactTitle": "Owner",
  "address": "Calle falsa 123",
  "city": "Madrid",
  "region": "",
  "postalCode": "28000",
  "country": "Spain",
  "phone": "123456789",
  "fax": "",
  "homepage": ""
}

> {%
    client.assert(response.status === 403, "No se ha creado, el usuario no tiene permisos");

    client.log(response.body);
%}



### Login
POST {{endpointLogin}}
Content-Type: application/json

{
  "username": "{{userWarehouse}}",
  "password": "{{pass}}"
}

> {%
    client.assert(response.status === 200, "El login falló");
    let jwt = response.body["token"];
    // Guardamos el token en una variable global de IntelliJ
    client.global.set("auth_token", jwt);

    client.log("¡Token capturado con éxito!");
%}


### Crear
POST {{endpoint}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "supplierId": {{id}},
  "companyName": "Nombre falso",
  "contactName": "Alguien",
  "contactTitle": "Owner",
  "address": "Calle falsa 123",
  "city": "Madrid",
  "region": "",
  "postalCode": "28000",
  "country": "Spain",
  "phone": "123456789",
  "fax": "",
  "homepage": ""
}

> {%
    client.assert(response.status === 201, "No se ha creado, el usuario no tiene permisos");

    client.log(response.body);
%}


### Probar verificar creacion
GET {{endpoint}}/{{id}}
Authorization: Bearer {{auth_token}}


### Actualizar (hay que enviar todo el objeto)
PUT {{endpoint}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "supplierId": {{id}},
  "companyName": "Nombre falso",
  "contactName": "Alguien",
  "contactTitle": "Empleado mentiroso",
  "address": "Calle falsa 1234",
  "city": "Madrid",
  "region": "",
  "postalCode": "28010",
  "country": "Spain",
  "phone": "123456789",
  "fax": "",
  "homepage": ""
}


### Borrar
DELETE {{endpoint}}/{{id}}
Authorization: Bearer {{auth_token}}


### Comprobar borrado
GET {{endpoint}}/{{id}}
Authorization: Bearer {{auth_token}}