@endpointLogin = {{host}}/auth/login
@endpoint = {{host}}/us-states

### Login
POST {{endpointLogin}}
Content-Type: application/json

{
  "username": "{{userGestor}}",
  "password": "{{pass}}"
}

> {%
    client.assert(response.status === 200, "El login falló");
    let jwt = response.body["token"];
    // Guardamos el token en una variable global de IntelliJ
    client.global.set("auth_token", jwt);

    client.log("¡Token capturado con éxito!");
%}


### Probar endpoint de traer todos
GET {{endpoint}}
# Aquí inyectamos la variable que acabamos de guardar
Authorization: Bearer {{auth_token}}


### Probar traer solo 1
GET {{endpoint}}/1
Authorization: Bearer {{auth_token}}



### Crear
POST {{endpoint}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "stateName": "Estado Falso",
  "stateAbbr": "es",
  "stateRegion": "center"
}

> {%
    client.assert(response.status === 201, "No se ha creado el estado");

    let nuevoId = response.body["stateId"];

    // Lo guardamos en una variable global
    client.global.set("created_state_id", nuevoId);

    client.log("Estado creado con el ID: " + nuevoId);
%}

### Probar verificar creacion del estado
GET {{endpoint}}/{{created_state_id}}
Authorization: Bearer {{auth_token}}


### Actualizamos el estado
PUT {{endpoint}}/{{created_state_id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "stateName": "Falso estado modificado",
  "stateAbbr": "fe",
  "stateRegion": "center"
}

### Borrar el estado
DELETE {{endpoint}}/{{created_state_id}}
Authorization: Bearer {{auth_token}}


### Probar borrado del estado (Debería dar 404)
GET {{endpoint}}/{{created_state_id}}
Authorization: Bearer {{auth_token}}