### Login como ADMIN
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "{{userAdmin}}",
  "password": "{{pass}}"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### Crear un nuevo usuario (Solo ADMIN)
POST {{host}}/users
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "username": "nuevo_usuario",
  "password": "password123",
  "role": "ROLE_USER",
  "employeeId": 1
}

### Listar todos los usuarios
GET {{host}}/users
Authorization: Bearer {{auth_token}}

### Habilitar/Deshabilitar usuario
PATCH {{host}}/users/1/status
Content-Type: application/json
Authorization: Bearer {{auth_token}}

false

### NOTA: Asegúrate de inyectar el token JWT en la cabecera Authorization: Bearer <token>
