-- Categorías
ALTER TABLE public.categories ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public.categories', 'category_id'), coalesce(max(category_id), 0) + 1, false) FROM public.categories;

-- Empleados
ALTER TABLE public.employees ALTER COLUMN employee_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public.employees', 'employee_id'), coalesce(max(employee_id), 0) + 1, false) FROM public.employees;

-- Región
ALTER TABLE public.region ALTER COLUMN region_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public.region', 'region_id'), coalesce(max(region_id), 0) + 1, false) FROM public.region;

-- Transportistas (Shippers)
ALTER TABLE public.shippers ALTER COLUMN shipper_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public.shippers', 'shipper_id'), coalesce(max(shipper_id), 0) + 1, false) FROM public.shippers;

-- Pedidos (Orders)
ALTER TABLE public.orders ALTER COLUMN order_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public.orders', 'order_id'), coalesce(max(order_id), 0) + 1, false) FROM public.orders;

-- Proveedores (Suppliers)
ALTER TABLE public.suppliers ALTER COLUMN supplier_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public.suppliers', 'supplier_id'), coalesce(max(supplier_id), 0) + 1, false) FROM public.suppliers;

-- Productos
ALTER TABLE public.products ALTER COLUMN product_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public.products', 'product_id'), coalesce(max(product_id), 0) + 1, false) FROM public.products;

-- Estados de EE.UU. (us_states)
ALTER TABLE public.us_states ALTER COLUMN state_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public.us_states', 'state_id'), coalesce(max(state_id), 0) + 1, false) FROM public.us_states;
